title: Saptarshi Ghosh
logo: assets/img/8B90D40C-5480-45D6-AB5B-62A68F88BD5D-27857-00000A1C5B36C3CA.jpeg
description: Data Scientist|Machine Learning Engineer|Tableau|SQL|Deep Learning
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
