title: Saptarshi Ghosh
logo: https://github.com/imsaptarshi91/portfolio/commit/abc47152088c0fddbdbb8c818c004e63d54db90b#commitcomment-133655822
description: Data Scientist|Machine Learning Engineer|Tableau|SQL|Deep Learning
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
